version: '3.9'

services:
    database:
        container_name: product-db
        image: postgres:alpine
        environment:
            POSTGRES_DB: product
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - '5431:5432'
        volumes:
            - '$PWD/docker/postgres/initdb.d/:/docker-entrypoint-initdb.d/'
